common:
  dd: ""
  mm: ""
  mm_str: ""
  yyyy: ""
  base_dir: ""
  business_date: "<dd><mm><yyyy>"
  business_date_month: "<dd><mm_str><yyyy>"
  eq_segment: "EQUITIES"
  derivaties_segment:  "DERIVATIVES"
  indices_segment: "indices"
  holiday_file: "<base_dir>/configs/holiday.json"
  data_and_reports: "DataAndReports"
  historical_data: "HistoricalData"
  reports_dir: "Reports"
  nse_base_url: "https://archives.nseindia.com/content"
  nifty_companies_dir: "<base_dir>/<data_and_reports>/<historical_data>/nifty_companies"
  graphs_dir: "<base_dir>/<data_and_reports>/Graphs"

job_list:
  - equity
  - fno
  - indices
  - emas
  - bell_curve
  - correlation_pairs
  - weekly_performance
  - monthly_performance
  - pnl

jobs:
  equity:
    tasks:
      - download_bhavcopy
      - nifty_50
      - nifty_next_50
      - nifty_mid_150
      - nifty_small_250
    params:
      trading_day: 50
      nse_endpoint: "<nse_base_url>/historical/<eq_segment>/<yyyy>/<mm_str>/cm<business_date_month>bhav.csv.zip"
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
      with_ema: False
      ema:
        - 9
        - 21
  fno:
    tasks:
      - futures
      - options
      - open_interest
    params:
      trading_day: 50
      futures: ''
      nse_endpoint: "<nse_base_url>/historical/<derivaties_segment>/<yyyy>/<mm_str>/fo<business_date_month>bhav.csv.zip"
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/fno"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/fno"
      open_interest_report: True
      with_ema: False
      ema:
        - 9
        - 21


  indices:
    tasks:
      - download_bhavcopy
      - nifty_index
    params:
      trading_day: 50
      nse_endpoint: "<nse_base_url>/<indices_segment>/ind_close_all_<business_date>.csv"
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/indices"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/indices"
      with_ema: False
      ema:
        - 9
        - 21 
  emas:
    tasks:
      - download_bhavcopy
      - ema_9_21
      - ema_25_50
      - ema_50_100
      - ema_100_200
      - ema_21_50_100_200
    params:
      nse_endpoint: "<nse_base_url>/historical/<eq_segment>/<yyyy>/<mm_str>/cm<business_date_month>bhav.csv.zip"
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
  bell_curve:
    tasks:
    params:
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
  correlation_pairs:
    tasks:
    params:
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
  
  weekly_performance:
    tasks:
    params:
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
  monthly_performance:
    tasks:
    params:
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/equity"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/equity"
  pnl:
    tasks:
      - calculate_pnl
    params:
      historical_data: "<base_dir>/<data_and_reports>/<historical_data>/pnl"
      reports: "<base_dir>/<data_and_reports>/<reports_dir>/pnl"
